#!/usr/bin/env bash

c_no_n="bcdfghjklmpqrstvwxyz"
uc_no_n="$(tr a-z A-Z <<<"$c_no_n")"
v="aeiou"
uv="$(tr a-z A-Z <<<"$v")"

exec sed -E -e 's/([Nn][Yy]?['"${uv}${v}"']|['"${uc_no_n}${c_no_n}"']*['"${uv}${v}"'Nn])[^A-Za-z]*/|&/g; s/^\|//' "$@"
